### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by IzzySoft** [stevep99/keyboard-layout-companion#2]
Your Readme says "Download from Google Play" – but Google Play does not offer a download for your app unless one has a Google account plus the GApps installed on-device, which some devices don't have (either because of the vendor not having put them, say Huawei – or because the device owner explicitly didn't want them, eg. for privacy reasons). Plus there are places where Play Store cannot be accessed from for other reasons.

So would you consider also providing the APK by other means? Most common for FOSS projects here is to [tag their releases](https://github.com/stevep99/keyboard-layout-companion/releases) and attach the APKs there – which is where most people also would look first.

Thanks in advance!

**Comment by stevep99** [comment]
Hi, yeah I should probably do that.

In the meantime you can download it direct from other third parties, e.g. APKPure https://m.apkpure.com/keyboard-layout-companion/io.github.colemakmods.keyboard_companion

**Comment by IzzySoft** [comment]
Thanks! But I'll have to wait for the APKs at your future tagged releases. My framework cannot deal with all the other available alternative download possibilities (for some background: the idea behind my request was to make your app available [in my repo](https://apt.izzysoft.de/fdroid), which fetches updates automatically and makes them available for folks using an F-Droid client).

**Comment by IzzySoft** [comment]
@stevep99 any chance you could tag your releases and attach the APKs to their corresponding tags (starting with the latest release, no need to go "back to Adam and Eve")?

**Comment by stevep99** [comment]
Yep, finally managed to do that.

**Comment by IzzySoft** [comment]
Great, thanks! So [here you go](https://apt.izzysoft.de/packages/io.github.colemakmods.keyboard_companion/) (becoming available with the next sync around 5 pm UTC – updates being pulled within 24h of your making the APK available at a new tag). Should you like what you see, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme. Folks using my repo with their F-Droid client then get updates automatically. Including some extra "security checks" :smiley:
